### ISSUE TITLE
Extra: Hide certificate options when certificate path is not selected

### ISSUE THREAD

**Issue by dstjohniii** [dstjohniii/ms-advisor#57]
When you have not selected the certificate path we should not show the certificate options.

**Comment by gwallace04** [comment]
We wouldn't want to necessarily hide the certificate options, since someone who is doing the traditional/professional option still might want to complete a certificate (e.g me). However, we should force the user to select at least one certificate if the certificate option is selected.

**Comment by dstjohniii** [comment]
@gwallace04 i didn't think we were supporting more than one career path at first to reduce complexity when creating the degree checklist.
